package com.chess;

public enum GameState {
    ONGOING,
    CHECKMATE_WHITE,
    CHECKMATE_BLACK,
    STALEMATE_WHITE,
    STALEMATE_BLACK,
    RESIGN_WHITE,
    RESIGN_BLACK,
    ONLY_KINGS,
    KING_KNIGHT_VS_KING,
    KING_BISHOP_VS_KING,
    KING_SAME_COLOR_BISHOPS_VS_KING

}
