package com.chess;

public enum GameState {
    ONGOING,
    DEAD_POSITION,
    CHECKMATE_WHITE,
    CHECKMATE_BLACK,
    STALEMATE_WHITE,
    STALEMATE_BLACK,
    RESIGN_WHITE,
    RESIGN_BLACK,
    STANDARD_DRAW_OFFER_ACCEPTED,
    FIFTY_MOVE_DRAW_CLAIMED,
    SEVENTY_FIVE_MOVE_RULE_DRAW,
    THREEFOLD_REPETITION_DRAW_CLAIMED,
    FIVEFOLD_REPETITION_RULE_DRAW,
    INSUFFICIENT_MATERIAL
}
